# Generated by Django 5.1.1 on 2024-10-18 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostesSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('localisation', models.CharField(max_length=255)),
                ('capacite', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Depart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('capacite', models.FloatField()),
                ('postes_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departs', to='surveillance.postessource')),
            ],
        ),
        migrations.CreateModel(
            name='Transformateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('caracteristiques', models.TextField(blank=True, null=True)),
                ('puissance', models.FloatField()),
                ('tension_secondaire', models.FloatField()),
                ('courant_secondaire', models.FloatField()),
                ('temperature_Huile', models.FloatField(blank=True, null=True)),
                ('niveau_Huile', models.IntegerField(blank=True, null=True)),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformateurs', to='surveillance.depart')),
            ],
        ),
    ]
