# Generated by Django 5.1.1 on 2024-10-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transformateur',
            name='courant_secondaire',
            field=models.TextField(),
        ),
    ]
