# Generated by Django 5.1.1 on 2024-10-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0002_alter_transformateur_courant_secondaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transformateur',
            name='courant_secondaire',
            field=models.TextField(blank=True, null=True),
        ),
    ]
