# Generated by Django 5.1.1 on 2024-10-19 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0003_alter_transformateur_courant_secondaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosteSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('localisation', models.CharField(max_length=255)),
                ('capacite', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='transformateur',
            old_name='nom',
            new_name='code_poste',
        ),
        migrations.AlterField(
            model_name='depart',
            name='postes_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departs', to='surveillance.postesource'),
        ),
        migrations.DeleteModel(
            name='PostesSource',
        ),
    ]
