# Generated by Django 5.1.1 on 2024-10-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0004_postesource_rename_nom_transformateur_code_poste_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transformateur',
            old_name='temperature_Huile',
            new_name='temperature',
        ),
        migrations.RemoveField(
            model_name='transformateur',
            name='niveau_Huile',
        ),
        migrations.AlterField(
            model_name='depart',
            name='capacite',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='postesource',
            name='capacite',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transformateur',
            name='code_poste',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='transformateur',
            name='courant_secondaire',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transformateur',
            name='tension_secondaire',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transformateur',
            name='niveau_huile',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
