# Generated by Django 5.1.1 on 2024-10-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0005_rename_temperature_huile_transformateur_temperature_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depart',
            old_name='postes_source',
            new_name='poste_source',
        ),
        migrations.AlterField(
            model_name='transformateur',
            name='puissance',
            field=models.CharField(max_length=100),
        ),
    ]
