# Generated by Django 5.1.1 on 2024-11-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0006_rename_postes_source_depart_poste_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformateur',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
