# Generated by Django 5.1.1 on 2024-12-01 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0007_transformateur_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transformateur',
            name='courant_secondaire',
        ),
        migrations.RemoveField(
            model_name='transformateur',
            name='niveau_huile',
        ),
        migrations.RemoveField(
            model_name='transformateur',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='transformateur',
            name='tension_secondaire',
        ),
        migrations.RemoveField(
            model_name='transformateur',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='transformateur',
            name='code_poste',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='transformateur',
            name='puissance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='HistoriqueDonnees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('pression_interne', models.FloatField()),
                ('courant_secondaire', models.FloatField()),
                ('temperature', models.FloatField()),
                ('niveau_huile', models.FloatField()),
                ('alerte', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True, null=True)),
                ('transformateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='surveillance.transformateur')),
            ],
        ),
    ]
